// Generated by CoffeeScript 1.8.0
(function() {
  var fibrous, fibrousify, nodeify;

  fibrous = require('use-global-fibrous');

  nodeify = function(p) {
    "Nodeifies a Promise";
    return function(callback) {
      return p.then(function(result) {
        return typeof callback === "function" ? callback(null, result) : void 0;
      }, function(err) {
        return typeof callback === "function" ? callback(err) : void 0;
      });
    };
  };

  fibrousify = function(P) {
    "Takes in a Promise implementation and adds `psync` and `pfuture` methods\nto instances of it";
    if (P.prototype.psync == null) {
      P.prototype.psync = function() {
        var f;
        f = nodeify(this);
        return f.sync();
      };
    }
    if (P.prototype.pfuture == null) {
      P.prototype.pfuture = function() {
        var f;
        f = nodeify(this);
        return f.future();
      };
    }
    return P;
  };

  module.exports = fibrousify;

}).call(this);
